### ISSUE TITLE
Namespaces missing in compiled DLL

### ISSUE THREAD

**Issue by tonedogsauce** [zeevl/Renci.SshNet#1]
Hello zeevl,

There are namespaces within Renci.SshNet that are unavailable in the compiled DLL.
    Channels
    NetConf
    Sftp.Requests
    Sftp.Responses

I have downloaded the source files from your repo and tried compiling it myself to no avail.

These Classes simply don't expose themselves through the Object Browser nor through any 'Using' statements.

I am hoping to reach out to you to work on a solution.

Thanks,

Tony

**Comment by zeevl** [comment]
hey @tonedogsauce,

Thanks for the issue and sorry for the delay, I just saw this. 

I'm not really maintaining this repo; it was simply forked from https://sshnet.codeplex.com/ with some minor modifications for my own purposes.   

The namespaces you mentioned don't get exported as they appear to be marked as `internal`.   Feel free to fork this repo and make any changes you need!

Steve
